default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("POSTGRES_DB", "postgresql_db") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgresql_user") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgresql_password") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "postgres") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "postgresql_db") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "postgresql_db") %>_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "postgresql_db") %>_production
